### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by purotoko321** [purotoko321/housework#1]

**Comment by purotoko321** [comment]
housework
├── README.md
├── front
├── back
└── docker-compose.yml

**Comment by purotoko321** [comment]
```
cd ./back
bundle init
```

**Comment by purotoko321** [comment]
```
# Gemfile
gem 'rails', '6.0.3'
```

**Comment by purotoko321** [comment]
Dockerfile
./back 
```
# zenn-app/back/Dockerfiles
FROM ruby:2.6.6

# 必要パッケージのダウンロード
ENV RUNTIME_PACKAGES="linux-headers libxml2-dev make gcc libc-dev nodejs tzdata mysql-dev mysql-client yarn" \
    DEV_PACKAGES="build-base curl-dev" 

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN mkdir /app
WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock


RUN apt-get update -qq 
RUN apt-get install -y build-essential libpq-dev
RUN gem install bundler:2.0.1

RUN bundle install

ADD . /app
```

**Comment by purotoko321** [comment]
docker-compose.yml
```
version: "3"

services:
  db:
    container_name: db
    image: mysql:5.7.30
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

  backend:
    container_name: backend
    build: ./backend/
    image: backend
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app:cached
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - 5000:3000 # ポートフォワード
    networks:
      app_net:
        ipv4_address: '172.20.0.3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

volumes:
  mysql_data:
  bundle_data:
```
